# Generated by Django 6.0.4 on 2026-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
    ]
